### ISSUE TITLE
Any chance of a public maven release?

### ISSUE THREAD

**Issue by frkline** [robshep/JavaFPE#1]
Also, any planned roadmap or updates?

Thanks!

**Comment by robshep** [comment]
Hi, 

no plans.

Feel free to fork and adapt as you wish? If you think you can make a useful additon and you want to contribute back, I'll happily merge PRs.  
I don't know how to make a maven central submission, but if you think it would be useful, then please feel free to kick it off :)

R

**Comment by frkline** [comment]
Thanks for checking in! We'll add a task to our internal queue; should make life much easier having a loop of updates/usage. 

Great work on this, by the way.
